//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpsellManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_174866_MiniProj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products_174866_MiniProj()
        {
            this.ProductsRecommend_174866_MiniProj = new HashSet<ProductsRecommend_174866_MiniProj>();
            this.ShoppingCart_174866_MiniProj = new HashSet<ShoppingCart_174866_MiniProj>();
        }
    
        public int ProductsId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ModelNumber { get; set; }
        public string ModelName { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public string Description { get; set; }
        public string imageUrl { get; set; }
    
        public virtual Categories_174866_MiniProj Categories_174866_MiniProj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsRecommend_174866_MiniProj> ProductsRecommend_174866_MiniProj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart_174866_MiniProj> ShoppingCart_174866_MiniProj { get; set; }
    }
}
