//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpsellManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsRecommend_174866_MiniProj
    {
        public int ProductsRecId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ModelNumber { get; set; }
        public string ModelName { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public string Description { get; set; }
        public string imageUrl { get; set; }
    
        public virtual Categories_174866_MiniProj Categories_174866_MiniProj { get; set; }
        public virtual Products_174866_MiniProj Products_174866_MiniProj { get; set; }
    }
}
