//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpsellManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTax_174866_MiniProj
    {
        public int SalesTaxId { get; set; }
        public string State { get; set; }
        public string County { get; set; }
        public string City { get; set; }
        public string Jurisdiction { get; set; }
        public Nullable<int> SalesTax { get; set; }
    }
}
