//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpsellManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart_174866_MiniProj
    {
        public int cartId { get; set; }
        public Nullable<int> productId { get; set; }
        public string cartImageUrl { get; set; }
        public string cartModelName { get; set; }
        public Nullable<int> productPrice { get; set; }
    
        public virtual Products_174866_MiniProj Products_174866_MiniProj { get; set; }
    }
}
